name: Feature💡
description: Suggest us a feature🌤
title: "[Feature]: Your new suggestion's brief description goes here"
labels: [feature]
assignees:
  - unassigned
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling this form, We'll implement the feature .
  - type: input
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: Ex. I'm always frustated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: multimedia
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Please upload your multimedia(screenshots or video) here
      
